# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='order',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='drink',
        ),
        migrations.AddField(
            model_name='order',
            name='drink',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(to='app.Menu'),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
