# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161021_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
