# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20161022_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table_number',
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='table_number',
            field=models.CharField(choices=[('a1', 'a1'), ('a2', 'a2'), ('a3', 'a3'), ('a4', 'a4'), ('b1', 'b1'), ('b2', 'b2'), ('b3', 'b3'), ('b4', 'b4'), ('c1', 'c1'), ('c2', 'c2'), ('c3', 'c3'), ('c4', 'c4'), ('d1', 'd1'), ('d2', 'd2'), ('d3', 'd3'), ('d4', 'd4')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
