# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20161022_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed',
            field=models.BooleanField(choices=[(True, 'Completed'), (False, 'Incomplete')], default=False),
        ),
    ]
